######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 22 15:02:08 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
QT += widgets
QT += gui declarative

# Input
HEADERS += main.hh
HEADERS += netsocket.hh
SOURCES += main.cc
SOURCES += netsocket.cc
